### ISSUE TITLE
T+1 vs T+28

### ISSUE THREAD

**Issue by rodrigo2019** [PedroHCouto/UDACITY-ML-Engineer-Nanodegree-Project#1]
Oi Pedro, tudo bem? Estava procurando soluções mais rápidas que o AWS Forecast e acabei achando sua implementação utilizando o DeepAr. Parabéns pelo trabalho, tudo ficou bem explicado.
Eu estudei seu código e acredito ter encontrado um erro que acaba invalidando seus resultados.
Quando você diz T+28, significa que com N dados históricos até o dia 1º por exemplo o modelo seria capaz de prever 28 dias a frente, não é o que parece que você fez com o RandomForest e LSTM, no seu caso pra eu prever os dados do 3º dia por exemplo seria necessário os dados até o 2º dia pra ter como entrada do modelo, então não é possível prever o 3º até que o 2º ocorra, a não ser que você faça uma predição com retroalimentação com saída do modelo, mas não foi o caso. O que eu pude perceber é que seus modelos é T+1 validados em 28 amostras e é nesse ponto que entra a discrepância do resultado em relação ao deepAr, pois de fato o deepAr faz a predição de T+28, e um erro maior me parece totalmente aceitável, pois temos 28 saídas pra acertar e a incerteza de um futuro mais distante

**Comment by PedroHCouto** [comment]
Olá Rodrigo, tudo bem e ai? Fico feliz que você tenha gostado da explicação e torço pra que o trabalho tenha sido ruim mesmo com esses erros.
De fato o que você apontou invalidam a hipótese pra RF e pra LSTM. Possível seria retroalimentar o modelo com a previsão do dia X agregada aos dados para prever X + 1 e assim chegar a 28 dias ou qualquer quantidade desejada.
Como meu eu disse no inicio do trabalho, meu intuito maior era treinar a criação de modelos e deploy dos mesmos usando o SageMaker, assim criar uma observação descrevendo esse erro na explicação!
Valeu :)
